### ISSUE TITLE
java

### ISSUE THREAD

**Issue by 1433498251** [blackfrogxxoo/SchedulerView#2]
老师，有java版的吗

**Comment by blackfrogxxoo** [comment]
没有哦

**Comment by 1433498251** [comment]
> 没有哦

请问我加载的日程数据范围是2022-01-01 至 2023-01-01，为什么年月日会计算出2021年的

**Comment by 1433498251** [comment]
> 

清楚了，是因为触发checkMore的时候，当loadMore为true时，也将beginTime和endTime更新了
